inherit_from: .rubocop_todo.yml
require: 
  - rubocop-rails
  - rubocop-rspec
AllCops:
  DisabledByDefault: true
  Exclude:
    - Gemfile
    - bin/bundle
    - config/environments/**

Bundler/InsecureProtocolSource:
  Enabled: true
Security/Eval:
  Enabled: true
Security/JSONLoad:
  Enabled: true
Security/MarshalLoad:
  Enabled: true
Security/Open:
  Enabled: true
Security/YAMLLoad:
  Enabled: true
Style/Documentation:
  Enabled: true